/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.FajlbaController;
import model.Kartya;

/**
 *
 * @author PauluszKristófCsanád
 */
public class FajlbaView extends javax.swing.JFrame {

    public void listenHozzaad(FajlbaController.HozzaAdListener hozzaAdListener) {
        addBt.addActionListener(hozzaAdListener);
    }

    /**
     * Creates new form FajlbaView
     */
    public FajlbaView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kerdesField = new javax.swing.JTextField();
        KerdesLabel = new javax.swing.JLabel();
        valaszLabel = new javax.swing.JLabel();
        valaszField = new javax.swing.JTextField();
        addBt = new javax.swing.JButton();
        okBt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kerdesField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kerdesFieldActionPerformed(evt);
            }
        });

        KerdesLabel.setText("Kérdés:");

        valaszLabel.setText("Válasz:");

        valaszField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valaszFieldActionPerformed(evt);
            }
        });

        addBt.setText("Hozzáad");
        addBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtActionPerformed(evt);
            }
        });

        okBt.setText("OK");
        okBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(146, Short.MAX_VALUE)
                .addComponent(addBt)
                .addGap(144, 144, 144))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kerdesField)
                    .addComponent(valaszField)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(valaszLabel)
                            .addComponent(KerdesLabel)
                            .addComponent(okBt))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(KerdesLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kerdesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(valaszLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(valaszField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addBt)
                .addGap(18, 18, 18)
                .addComponent(okBt)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        KerdesLabel.getAccessibleContext().setAccessibleName("kerdesLabel");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kerdesFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kerdesFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kerdesFieldActionPerformed

    private void okBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_okBtActionPerformed

    private void valaszFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valaszFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valaszFieldActionPerformed

    private void addBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtActionPerformed
        kerdesField.setText("");
        valaszField.setText("");
    }//GEN-LAST:event_addBtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FajlbaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FajlbaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FajlbaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FajlbaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FajlbaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel KerdesLabel;
    private javax.swing.JButton addBt;
    private javax.swing.JTextField kerdesField;
    private javax.swing.JButton okBt;
    private javax.swing.JTextField valaszField;
    private javax.swing.JLabel valaszLabel;
    // End of variables declaration//GEN-END:variables

    public Kartya getKartya() {
        return new Kartya(kerdesField.getText(), valaszField.getText());
    }

    public void listenElfogad(FajlbaController.ElfogadListener elfogadListener) {
        okBt.addActionListener(elfogadListener);
    }
}
